# Auto-report action script, 3 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '35 13,15,18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        EMERGENCY_DATA: ${{ secrets.Emergency_Data }}
        BAIDU_AK: ${{ secrets.Baidu_AK}}
        BAIDU_SK: ${{ secrets.Baidu_SK}}
        DORMITORY_DATA: ${{ secrets.DORMITORY_DATA }}
      run: |
        python report.py data.json application.json "$STUID" "$PASSWORD" "$EMERGENCY_DATA" "$BAIDU_AK" "$BAIDU_SK" "$DORMITORY_DATA"
