# Auto-report action script, 3 times a day

name: Auto-report action

on: 
  push:
    branches:
      - master
  schedule:
    - cron: '35 7,13,19 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get install tesseract-ocr
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run report script
      env:
        STUID: ${{ secrets.Stuid }}
        PASSWORD: ${{ secrets.Password }}
        EMERGENCY_DATA: ${{ secrets.Emergency_Data }}
      run: |
        python report.py data.json "$STUID" "$PASSWORD" "$EMERGENCY_DATA"
